import Handlebars from 'handlebars';
import { AgileProject } from '../../project-init/domain/entities';

// Handlebars helpers
Handlebars.registerHelper('getPersonaName', function(personaId: string, options: any) {
  const project = options.data.root.project as AgileProject;
  return project.personas.find(p => p.id === personaId)?.name || 'Anonyme';
});

// Since reading files from disk during execution in a Vite/Node hybrid can be tricky 
// in this environment, I'll embed the templates here for the generator service.
const templates = {
  besoins: `
# ANALYSE DES BESOINS - {{projectName}}

## Contexte
{{projectDescription}}

## Objectifs Business
- Cadrer le projet en méthodologie Agile.
- Produire des livrables exploitables rapidement.

## Personas Identifiés
{{#each personas}}
### {{name}} ({{role}})
{{description}}
{{/each}}

---
Généré par AgileInit
`,
  user_stories: `
# USER STORIES - {{projectName}}

{{#each userStories}}
## US{{@index}}: {{role}}
**En tant que** {{role}}
**Je veux** {{action}}
**Afin de** {{benefit}}

*Statut : {{status}}*
*Persona : {{getPersonaName personaId}}*

---
{{/each}}
`,
  backlog: `
# PRODUCT BACKLOG - {{projectName}}

| ID | User Story | Persona | Priorité | Statut |
|:---|:---|:---|:---|:---|
{{#each userStories}}
| US{{@index}} | En tant que {{role}}, je veux {{action}} afin de {{benefit}} | {{getPersonaName personaId}} | Medium | {{status}} |
{{/each}}

---
Generated by AgileInit Strategic Engine.
`,
  stack: `
# STACK TECHNIQUE - {{projectName}}

## Backend
- Node.js
- TypeScript
- Express

## Frontend
- React
- Vite
- Stitch Design System (Kinetic Engine)

## Infrastructure & Qualité
- Vitest (Tests unitaires)
- Modular Architecture (Screaming)
- Standard Markdown Exports

---
Définition technique arrêtée le {{currentDate}}
`
};

export const generateDocs = (project: AgileProject) => {
  const context = {
    projectName: project.name,
    projectDescription: project.description,
    personas: project.personas,
    userStories: project.userStories,
    project: project, // For helper access
    currentDate: new Date().toLocaleDateString()
  };

  return {
    besoins: Handlebars.compile(templates.besoins)(context),
    user_stories: Handlebars.compile(templates.user_stories)(context),
    backlog: Handlebars.compile(templates.backlog)(context),
    stack: Handlebars.compile(templates.stack)(context),
    full: [
      Handlebars.compile(templates.besoins)(context),
      Handlebars.compile(templates.user_stories)(context),
      Handlebars.compile(templates.backlog)(context),
      Handlebars.compile(templates.stack)(context)
    ].join('\n\n---\n\n')
  };
};
